### ISSUE TITLE
DBコネクションが意図せず切断されないように TCP keepalive を短くする

### ISSUE THREAD

**Issue by tichi73** [fixpoint/ke2-docker#57]
Kompira と DB サーバ間のコネクションが途中経路などで意図せず切断されないように、TCP keepalive を短く設定する。
tcp_keepalive_time のデフォルトは 7200 (2時間) であり、ある環境ではこれではアイドル時に切断されてしまう（その後ジョブフローが正常動作しない）事象が発生した。当該環境では以下のように tcp_keepalive_time を 1800 (30分) にすることで、セッションが切れることが無くなった。

```
    sysctls:
      net.ipv4.tcp_keepalive_intvl: 75
      net.ipv4.tcp_keepalive_probes: 9
      net.ipv4.tcp_keepalive_time: 1800
```
※ 上記設定を docker-swarm.yml の DBアクセスするサービスに下記を追記して確認した。
